<a href="https://colab.research.google.com/github/sawao7/logistic_regression/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
li = ['3 1 4', '3 4 1', '2 2 2', '4 3 3']
print(li)

['3 1 4', '3 4 1', '2 2 2', '4 3 3']


In [4]:
w = 7

In [27]:
import numpy as np
# line = "6 5 5 5 6 5 6 6 5 6"
line = "87 98 48 58 59 97 43 100 96 73"
line = "73 78 91 78 27 92 79 93 85 89"
nums = list(map(int, line.split()))
print(nums)
# array = np.ndarray(nums)

[73, 78, 91, 78, 27, 92, 79, 93, 85, 89]


In [28]:
num = np.array(nums)
num

array([73, 78, 91, 78, 27, 92, 79, 93, 85, 89])

In [29]:
np.var(num)

338.45

In [30]:
df = [
      ["6 5 5 5 6 5 6 6 5 6",4],
      ["2 5 1 3 3 6 6 6 5 5",1 ],
      ["98 89 96 93 59 18 93 92 81 87", 3],
      ["96 57 52 83 80 50 44 92 82 94", 3],
      ["38 51 89 29 86 89 88 51 89 48", 2],
      ["78 98 86 94 63 72 92 95 89 87", 5],
      ["82 81 81 96 90 95 97 83 70 74", 5],
      ["69 92 78 66 84 94 100 71 83 79", 5],
      ["99 67 94 87 82 83 92 77 74 91", 4],
      ["53 91 87 50 78 60 75 86 100 95", 4],
      ["48 92 97 100 84 28 87 82 50 70", 2],
      ["80 69 80 88 68 83 86 89 71 66", 4],
      ["61 77 59 49 28 98 43 76 44 88", 3],
      ["53 83 62 99 98 94 96 92 83 95", 3],
      ["44 30 53 8 9 50 94 11 60 10", 1],
      ["95 82 92 99 80 91 96 89 82 95", 4],
      ["79 80 96 83 95 47 83 54 70 94", 3],
      ["82 67 96 62 97 80 54 31 97 58", 3],
      ["91 87 96 91 42 43 70 97 100 86", 3],
      ["80 92 93 94 91 83 97 91 88 83", 5],
      ["98 97 58 67 24 100 97 76 98 47", 2],
      ["86 72 95 76 89 93 69 88 72 99", 5],
      ["99 87 85 91 71 92 62 94 95 72", 4],
      ["61 26 98 79 80 74 93 100 68 81", 4],
      ["100 86 84 90 81 90 56 96 83 99", 5],
      ["90 14 81 57 72 57 49 53 60 84", 2],
      ["80 99 70 91 66 58 100 79 79 90", 4],
      ["62 83 77 83 91 75 94 98 85 79", 4],
      ["89 70 87 98 94 88 64 83 78 95", 5],
      ["66 73 78 100 90 98 83 96 55 99", 3],
      ["60 45 83 61 79 56 49 75 36 6", 1],
      ["71 74 87 9 81 74 94 82 72 5", 1],
]

In [35]:
import pandas as pd
data = pd.DataFrame(df, columns=["input","output"])

In [46]:
data["ndarray"] = data["input"].str.split().apply(lambda x: list(map(int, x))).apply(lambda x: np.array(x))

In [63]:
data["var"] = data["ndarray"].apply(lambda x: np.var(x))
data["mean"] = data["ndarray"].apply(lambda x: np.mean(x))
data["std"] = data["ndarray"].apply(lambda x: np.std(x))
data["sum"] = data["ndarray"].apply(lambda x: np.sum(x))
data["test"] = data["var"] / data["sum"]

In [64]:
data.corr()

output       var      mean       std      test       sum
output  1.000000 -0.721104  0.540610 -0.624289 -0.741744  0.540610
var    -0.721104  1.000000 -0.107955  0.967045  0.926697 -0.107955
mean    0.540610 -0.107955  1.000000  0.079396 -0.265455  1.000000
std    -0.624289  0.967045  0.079396  1.000000  0.866230  0.079396
test   -0.741744  0.926697 -0.265455  0.866230  1.000000 -0.265455
sum     0.540610 -0.107955  1.000000  0.079396 -0.265455  1.000000

In [111]:
df_train = data[["mean", "var"]]
df_test = data["output"]

In [112]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_train, df_test, test_size=0.3, random_state=0, stratify=df_test)

In [135]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
# 学習させる
# clf.fit(X_train, y_train)
clf.fit(df_train, df_test)


# print('正解',y_test)
# 学習したデータと比較して推測する
print('推測した結果',clf.predict(df_train))
print('推測した結果の正解率',clf.score(df_train,df_test))

推測した結果 [4 1 3 3 2 5 5 4 5 3 2 4 2 3 1 5 4 3 3 5 2 5 4 3 5 2 4 4 5 4 1 1]
推測した結果の正解率 0.75


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [159]:
a = clf.coef_
b = clf.intercept_ 
b

array([11.07960962, -2.89000856, -6.11182943,  4.96925065, -7.04702229])

In [153]:
df_test

0     4
1     1
2     3
3     3
4     2
5     5
6     5
7     5
8     4
9     4
10    2
11    4
12    3
13    3
14    1
15    4
16    3
17    3
18    3
19    5
20    2
21    5
22    4
23    4
24    5
25    2
26    4
27    4
28    5
29    3
30    1
31    1
Name: output, dtype: int64

In [171]:
import scipy
for i in range(1):
    print(df_train.values[i])
    print(a.T)
    # print(b)
    print(np.matmul(np.array([5.5, 0.25]), a.T))
    # print(np.matmul(df_train.values[i], a.T) + b)
    # print(np.argmax(scipy.special.softmax(np.matmul(df_train.values[i], a.T) + b)) + 1 == df_test[i])
np.__version__

[5.5  0.25]
[[-1.0424503  -0.05253795  0.37297032  0.28475073  0.4372672 ]
 [ 0.11256625  0.02259688 -0.03190046 -0.04791604 -0.05534664]]
[-5.70533509 -0.28330951  2.04336167  1.55415     2.39113293]


'1.21.6'